// SPDX-License-Identifier: GPL-3.0-or-later
// <auto-generated>
//   Generated from ranger's gui/context.py by tools/generate-context-keys.py.
//   Do not edit by hand.
// </auto-generated>
namespace Canger.Ui.Styling;

/// <summary>
/// The properties a colourscheme can colour by.
/// </summary>
/// <remarks>
/// Several of these apply to a cell at once — a row might be in the browser, in the main column,
/// a directory, and selected — and the colourscheme decides the result from the whole set rather
/// than from any one key. The names and the set match ranger's exactly, so a colourscheme ported
/// from there means the same thing here.
/// </remarks>
public enum ContextKey
{
    /// <summary>The <c>reset</c> context.</summary>
    Reset = 0,

    /// <summary>The <c>error</c> context.</summary>
    Error = 1,

    /// <summary>The <c>badinfo</c> context.</summary>
    BadInfo = 2,

    /// <summary>The <c>in_browser</c> context.</summary>
    InBrowser = 3,

    /// <summary>The <c>in_statusbar</c> context.</summary>
    InStatusbar = 4,

    /// <summary>The <c>in_titlebar</c> context.</summary>
    InTitlebar = 5,

    /// <summary>The <c>in_console</c> context.</summary>
    InConsole = 6,

    /// <summary>The <c>in_pager</c> context.</summary>
    InPager = 7,

    /// <summary>The <c>in_taskview</c> context.</summary>
    InTaskview = 8,

    /// <summary>The <c>active_pane</c> context.</summary>
    ActivePane = 9,

    /// <summary>The <c>inactive_pane</c> context.</summary>
    InactivePane = 10,

    /// <summary>The <c>directory</c> context.</summary>
    Directory = 11,

    /// <summary>The <c>file</c> context.</summary>
    File = 12,

    /// <summary>The <c>hostname</c> context.</summary>
    Hostname = 13,

    /// <summary>The <c>executable</c> context.</summary>
    Executable = 14,

    /// <summary>The <c>media</c> context.</summary>
    Media = 15,

    /// <summary>The <c>link</c> context.</summary>
    Link = 16,

    /// <summary>The <c>fifo</c> context.</summary>
    Fifo = 17,

    /// <summary>The <c>socket</c> context.</summary>
    Socket = 18,

    /// <summary>The <c>device</c> context.</summary>
    Device = 19,

    /// <summary>The <c>video</c> context.</summary>
    Video = 20,

    /// <summary>The <c>audio</c> context.</summary>
    Audio = 21,

    /// <summary>The <c>image</c> context.</summary>
    Image = 22,

    /// <summary>The <c>document</c> context.</summary>
    Document = 23,

    /// <summary>The <c>container</c> context.</summary>
    Container = 24,

    /// <summary>The <c>selected</c> context.</summary>
    Selected = 25,

    /// <summary>The <c>empty</c> context.</summary>
    Empty = 26,

    /// <summary>The <c>main_column</c> context.</summary>
    MainColumn = 27,

    /// <summary>The <c>message</c> context.</summary>
    Message = 28,

    /// <summary>The <c>background</c> context.</summary>
    Background = 29,

    /// <summary>The <c>good</c> context.</summary>
    Good = 30,

    /// <summary>The <c>bad</c> context.</summary>
    Bad = 31,

    /// <summary>The <c>space</c> context.</summary>
    Space = 32,

    /// <summary>The <c>permissions</c> context.</summary>
    Permissions = 33,

    /// <summary>The <c>owner</c> context.</summary>
    Owner = 34,

    /// <summary>The <c>group</c> context.</summary>
    Group = 35,

    /// <summary>The <c>mtime</c> context.</summary>
    Mtime = 36,

    /// <summary>The <c>nlink</c> context.</summary>
    LinkCount = 37,

    /// <summary>The <c>scroll</c> context.</summary>
    Scroll = 38,

    /// <summary>The <c>all</c> context.</summary>
    All = 39,

    /// <summary>The <c>bot</c> context.</summary>
    Bot = 40,

    /// <summary>The <c>top</c> context.</summary>
    Top = 41,

    /// <summary>The <c>percentage</c> context.</summary>
    Percentage = 42,

    /// <summary>The <c>filter</c> context.</summary>
    Filter = 43,

    /// <summary>The <c>flat</c> context.</summary>
    Flat = 44,

    /// <summary>The <c>marked</c> context.</summary>
    Marked = 45,

    /// <summary>The <c>tagged</c> context.</summary>
    Tagged = 46,

    /// <summary>The <c>tag_marker</c> context.</summary>
    TagMarker = 47,

    /// <summary>The <c>line_number</c> context.</summary>
    LineNumber = 48,

    /// <summary>The <c>cut</c> context.</summary>
    Cut = 49,

    /// <summary>The <c>copied</c> context.</summary>
    Copied = 50,

    /// <summary>The <c>frozen</c> context.</summary>
    Frozen = 51,

    /// <summary>The <c>help_markup</c> context.</summary>
    HelpMarkup = 52,

    /// <summary>The <c>seperator</c> context.</summary>
    Separator = 53,

    /// <summary>The <c>key</c> context.</summary>
    Key = 54,

    /// <summary>The <c>special</c> context.</summary>
    Special = 55,

    /// <summary>The <c>border</c> context.</summary>
    Border = 56,

    /// <summary>The <c>title</c> context.</summary>
    Title = 57,

    /// <summary>The <c>text</c> context.</summary>
    Text = 58,

    /// <summary>The <c>highlight</c> context.</summary>
    Highlight = 59,

    /// <summary>The <c>bars</c> context.</summary>
    Bars = 60,

    /// <summary>The <c>quotes</c> context.</summary>
    Quotes = 61,

    /// <summary>The <c>tab</c> context.</summary>
    Tab = 62,

    /// <summary>The <c>loaded</c> context.</summary>
    Loaded = 63,

    /// <summary>The <c>keybuffer</c> context.</summary>
    KeyBuffer = 64,

    /// <summary>The <c>infostring</c> context.</summary>
    InfoString = 65,

    /// <summary>The <c>vcsfile</c> context.</summary>
    VcsFile = 66,

    /// <summary>The <c>vcsremote</c> context.</summary>
    VcsRemote = 67,

    /// <summary>The <c>vcsinfo</c> context.</summary>
    VcsInfo = 68,

    /// <summary>The <c>vcscommit</c> context.</summary>
    VcsCommit = 69,

    /// <summary>The <c>vcsdate</c> context.</summary>
    VcsDate = 70,

    /// <summary>The <c>vcsconflict</c> context.</summary>
    VcsConflict = 71,

    /// <summary>The <c>vcschanged</c> context.</summary>
    VcsChanged = 72,

    /// <summary>The <c>vcsunknown</c> context.</summary>
    VcsUnknown = 73,

    /// <summary>The <c>vcsignored</c> context.</summary>
    VcsIgnored = 74,

    /// <summary>The <c>vcsuntracked</c> context.</summary>
    VcsUntracked = 75,

    /// <summary>The <c>vcsstaged</c> context.</summary>
    VcsStaged = 76,

    /// <summary>The <c>vcssync</c> context.</summary>
    VcsSync = 77,

    /// <summary>The <c>vcsnone</c> context.</summary>
    VcsNone = 78,

    /// <summary>The <c>vcsbehind</c> context.</summary>
    VcsBehind = 79,

    /// <summary>The <c>vcsahead</c> context.</summary>
    VcsAhead = 80,

    /// <summary>The <c>vcsdiverged</c> context.</summary>
    VcsDiverged = 81,

}

/// <summary>Maps context keys to and from the names used in configuration.</summary>
public static class ContextKeys
{
    /// <summary>How many keys there are.</summary>
    public const int Count = 82;

    private static readonly string[] NamesByKey =
    [
        "reset",
        "error",
        "badinfo",
        "in_browser",
        "in_statusbar",
        "in_titlebar",
        "in_console",
        "in_pager",
        "in_taskview",
        "active_pane",
        "inactive_pane",
        "directory",
        "file",
        "hostname",
        "executable",
        "media",
        "link",
        "fifo",
        "socket",
        "device",
        "video",
        "audio",
        "image",
        "document",
        "container",
        "selected",
        "empty",
        "main_column",
        "message",
        "background",
        "good",
        "bad",
        "space",
        "permissions",
        "owner",
        "group",
        "mtime",
        "nlink",
        "scroll",
        "all",
        "bot",
        "top",
        "percentage",
        "filter",
        "flat",
        "marked",
        "tagged",
        "tag_marker",
        "line_number",
        "cut",
        "copied",
        "frozen",
        "help_markup",
        "seperator",
        "key",
        "special",
        "border",
        "title",
        "text",
        "highlight",
        "bars",
        "quotes",
        "tab",
        "loaded",
        "keybuffer",
        "infostring",
        "vcsfile",
        "vcsremote",
        "vcsinfo",
        "vcscommit",
        "vcsdate",
        "vcsconflict",
        "vcschanged",
        "vcsunknown",
        "vcsignored",
        "vcsuntracked",
        "vcsstaged",
        "vcssync",
        "vcsnone",
        "vcsbehind",
        "vcsahead",
        "vcsdiverged",
    ];

    /// <summary>The configuration name of a key.</summary>
    /// <param name="key">The key.</param>
    /// <returns>Its name, as ranger spells it.</returns>
    public static string NameOf(ContextKey key) => NamesByKey[(int)key];

    /// <summary>Every key, in declaration order.</summary>
    public static IReadOnlyList<ContextKey> All { get; } =
        [.. Enumerable.Range(0, Count).Select(i => (ContextKey)i)];
}
