// SPDX-License-Identifier: GPL-3.0-or-later
//
// Devicons for Canger — a glyph before each name saying what kind of file it is.
//
// Generated by tools/generate-devicons-plugin.py from ranger_devicons' devicons.py:
// 88 exact names, 227 extensions, 15 directory names. The glyphs
// and the tables are ranger_devicons' work, GPL-3.0, and the glyphs themselves come from Nerd
// Fonts. Without a patched font they render as replacement boxes.
//
// Registered as "devicons", which is the name the built-in linemode uses, so this replaces it —
// `LinemodeRegistry.Register` overwrites a mode of the same name. Turn it on with
// `default_linemode devicons` in cc.conf, or `:linemode devicons` for one directory.
//
// Adding your own: put it in the right table below and restart. A whole filename beats an
// extension, which is how Makefile and .gitignore work. Regenerating from a newer
// ranger_devicons overwrites this file, so keep additions in a second plugin that falls back to
// this one if you expect to regenerate.
using Canger.Core.Model;
using Canger.Core.State;

/// <summary>A glyph before each name, from ranger_devicons' tables.</summary>
public sealed class DeviconsPlugin : ILinemode
{
    /// <inheritdoc />
    public string Name => "devicons";

    /// <inheritdoc />
    public string Title(FsNode node, FileMetadata metadata, in LinemodeContext context)
    {
        ArgumentNullException.ThrowIfNull(node);

        return Glyph(node) + " " + node.RelativePath;
    }

    /// <inheritdoc />
    /// <remarks>
    /// Null rather than a value: the column falls back to the size, so this mode changes the name
    /// and leaves the right-hand side as an ordinary listing shows it.
    /// </remarks>
    public string? Detail(FsNode node, FileMetadata metadata, in LinemodeContext context) => null;

    /// <summary>The glyph for an entry.</summary>
    /// <param name="node">The entry.</param>
    /// <returns>A single glyph, or a generic one when nothing matches.</returns>
    public static string Glyph(FsNode node)
    {
        ArgumentNullException.ThrowIfNull(node);

        string name = node.RelativePath;

        if (node.IsDirectory)
        {
            return Directories.TryGetValue(name, out string? directory)
                ? directory
                : GenericDirectory;
        }

        // A whole filename beats an extension: Makefile and .gitignore have no useful extension,
        // and Dockerfile would otherwise look like any other extensionless file.
        if (ExactNames.TryGetValue(name, out string? byName))
        {
            return byName;
        }

        string extension = System.IO.Path.GetExtension(name);

        return extension.Length > 1 && Extensions.TryGetValue(extension[1..], out string? byKind)
            ? byKind
            : GenericFile;
    }

    /// <summary>Shown for a file nothing else matches.</summary>
    private const string GenericFile = "";

    /// <summary>Shown for a directory nothing else matches.</summary>
    private const string GenericDirectory = "";

    /// <summary>Glyphs by whole filename.</summary>
    private static readonly Dictionary<string, string> ExactNames =
        new(StringComparer.OrdinalIgnoreCase)
    {
        [".DS_Store"] = "",
        [".Xauthority"] = "",
        [".Xdefaults"] = "",
        [".Xresources"] = "",
        [".bash_aliases"] = "",
        [".bash_history"] = "",
        [".bash_logout"] = "",
        [".bash_profile"] = "",
        [".bashprofile"] = "",
        [".bashrc"] = "",
        [".dmrc"] = "",
        [".fasd"] = "",
        [".fehbg"] = "",
        [".gitattributes"] = "",
        [".gitconfig"] = "",
        [".gitignore"] = "",
        [".gitlab-ci.yml"] = "",
        [".gvimrc"] = "",
        [".inputrc"] = "",
        [".jack-settings"] = "",
        [".mime.types"] = "",
        [".ncmpcpp"] = "",
        [".nvidia-settings-rc"] = "",
        [".pam_environment"] = "",
        [".profile"] = "",
        [".recently-used"] = "",
        [".selected_editor"] = "",
        [".vim"] = "",
        [".viminfo"] = "",
        [".vimrc"] = "",
        [".xinitrc"] = "",
        [".xinputrc"] = "",
        [".zshrc"] = "",
        ["Dockerfile"] = "",
        ["LICENSE"] = "",
        ["LICENSE.md"] = "",
        ["LICENSE.txt"] = "",
        ["Makefile"] = "",
        ["Makefile.ac"] = "",
        ["Makefile.in"] = "",
        ["README"] = "",
        ["README.markdown"] = "",
        ["README.md"] = "",
        ["README.rst"] = "",
        ["README.txt"] = "",
        ["Rakefile"] = "",
        ["_gvimrc"] = "",
        ["_vimrc"] = "",
        ["a.out"] = "",
        ["authorized_keys"] = "",
        ["bspwmrc"] = "",
        ["cmakelists.txt"] = "",
        ["config"] = "",
        ["config.ac"] = "",
        ["config.m4"] = "",
        ["config.mk"] = "",
        ["config.ru"] = "",
        ["configure"] = "",
        ["docker-compose.yml"] = "",
        ["dockerfile"] = "",
        ["dropbox"] = "",
        ["exact-match-case-sensitive-1.txt"] = "X1",
        ["exact-match-case-sensitive-2"] = "X2",
        ["favicon.ico"] = "",
        ["gemfile"] = "",
        ["gruntfile.coffee"] = "",
        ["gruntfile.js"] = "",
        ["gruntfile.ls"] = "",
        ["gulpfile.coffee"] = "",
        ["gulpfile.js"] = "",
        ["gulpfile.ls"] = "",
        ["ini"] = "",
        ["known_hosts"] = "",
        ["ledger"] = "",
        ["license"] = "",
        ["makefile"] = "",
        ["mimeapps.list"] = "",
        ["mix.lock"] = "",
        ["node_modules"] = "",
        ["package-lock.json"] = "",
        ["package.json"] = "",
        ["playlists"] = "",
        ["procfile"] = "",
        ["rakefile"] = "",
        ["react.jsx"] = "",
        ["sxhkdrc"] = "",
        ["user-dirs.dirs"] = "",
        ["webpack.config.js"] = "",
    };

    /// <summary>Glyphs by extension, without the dot.</summary>
    private static readonly Dictionary<string, string> Extensions =
        new(StringComparer.OrdinalIgnoreCase)
    {
        ["7z"] = "",
        ["a"] = "",
        ["ai"] = "",
        ["apk"] = "",
        ["asm"] = "",
        ["asp"] = "",
        ["aup"] = "",
        ["avi"] = "",
        ["awk"] = "",
        ["bash"] = "",
        ["bat"] = "",
        ["bmp"] = "",
        ["bz2"] = "",
        ["c"] = "",
        ["c++"] = "",
        ["cab"] = "",
        ["cbr"] = "",
        ["cbz"] = "",
        ["cc"] = "",
        ["class"] = "",
        ["clj"] = "",
        ["cljc"] = "",
        ["cljs"] = "",
        ["cmake"] = "",
        ["coffee"] = "",
        ["conf"] = "",
        ["cp"] = "",
        ["cpio"] = "",
        ["cpp"] = "",
        ["cs"] = "󰌛",
        ["csh"] = "",
        ["css"] = "",
        ["cue"] = "",
        ["cvs"] = "",
        ["cxx"] = "",
        ["d"] = "",
        ["dart"] = "",
        ["db"] = "",
        ["deb"] = "",
        ["diff"] = "",
        ["dll"] = "",
        ["doc"] = "",
        ["docm"] = "",
        ["docx"] = "",
        ["dotm"] = "",
        ["dotx"] = "",
        ["dps"] = "",
        ["dpt"] = "",
        ["drawio"] = "󰇟",
        ["dump"] = "",
        ["edn"] = "",
        ["eex"] = "",
        ["efi"] = "",
        ["ejs"] = "",
        ["elf"] = "",
        ["elm"] = "",
        ["epub"] = "",
        ["erl"] = "",
        ["et"] = "󰈛",
        ["ett"] = "󰈛",
        ["ex"] = "",
        ["exe"] = "",
        ["exs"] = "",
        ["f#"] = "",
        ["fifo"] = "󰟥",
        ["fish"] = "",
        ["flac"] = "",
        ["flv"] = "",
        ["fs"] = "",
        ["fsi"] = "",
        ["fsscript"] = "",
        ["fsx"] = "",
        ["gem"] = "",
        ["gemspec"] = "",
        ["gif"] = "",
        ["go"] = "",
        ["gz"] = "",
        ["gzip"] = "",
        ["h"] = "",
        ["haml"] = "",
        ["hbs"] = "",
        ["hh"] = "",
        ["hpp"] = "",
        ["hrl"] = "",
        ["hs"] = "",
        ["htaccess"] = "",
        ["htm"] = "",
        ["html"] = "",
        ["htpasswd"] = "",
        ["hxx"] = "",
        ["ico"] = "",
        ["img"] = "",
        ["ini"] = "",
        ["ipynb"] = "",
        ["iso"] = "",
        ["jar"] = "",
        ["java"] = "",
        ["jl"] = "",
        ["jpeg"] = "",
        ["jpg"] = "",
        ["js"] = "",
        ["json"] = "",
        ["jsonc"] = "",
        ["jsx"] = "",
        ["key"] = "",
        ["ksh"] = "",
        ["leex"] = "",
        ["less"] = "",
        ["lha"] = "",
        ["lhs"] = "",
        ["log"] = "",
        ["lua"] = "",
        ["lz"] = "",
        ["lzh"] = "",
        ["lzma"] = "",
        ["m4a"] = "",
        ["m4v"] = "",
        ["markdown"] = "",
        ["md"] = "",
        ["mdx"] = "",
        ["mjs"] = "",
        ["mka"] = "",
        ["mkv"] = "",
        ["ml"] = "λ",
        ["mli"] = "λ",
        ["mov"] = "",
        ["mp3"] = "",
        ["mp4"] = "",
        ["mpeg"] = "",
        ["mpg"] = "",
        ["msi"] = "",
        ["mustache"] = "",
        ["nix"] = "",
        ["o"] = "",
        ["odp"] = "",
        ["ods"] = "",
        ["odt"] = "",
        ["ogg"] = "",
        ["opus"] = "",
        ["part"] = "",
        ["pdf"] = "",
        ["php"] = "",
        ["pl"] = "",
        ["pm"] = "",
        ["png"] = "",
        ["pot"] = "",
        ["potm"] = "",
        ["potx"] = "",
        ["pp"] = "",
        ["pps"] = "",
        ["ppsm"] = "",
        ["ppsx"] = "",
        ["ppt"] = "",
        ["pptm"] = "",
        ["pptx"] = "",
        ["ps1"] = "",
        ["psb"] = "",
        ["psd"] = "",
        ["pub"] = "",
        ["py"] = "",
        ["pyc"] = "",
        ["pyd"] = "",
        ["pyo"] = "",
        ["r"] = "󰟔",
        ["rake"] = "",
        ["rar"] = "",
        ["rb"] = "",
        ["rc"] = "",
        ["rlib"] = "",
        ["rmd"] = "",
        ["rom"] = "",
        ["rpm"] = "",
        ["rproj"] = "󰗆",
        ["rs"] = "",
        ["rss"] = "",
        ["rtf"] = "",
        ["s"] = "",
        ["sass"] = "",
        ["scala"] = "",
        ["scss"] = "",
        ["sh"] = "",
        ["slim"] = "",
        ["sln"] = "",
        ["so"] = "",
        ["sql"] = "",
        ["styl"] = "",
        ["suo"] = "",
        ["svelte"] = "",
        ["swift"] = "",
        ["t"] = "",
        ["tar"] = "",
        ["tex"] = "󰙩",
        ["tgz"] = "",
        ["toml"] = "",
        ["torrent"] = "",
        ["ts"] = "",
        ["tsx"] = "",
        ["twig"] = "",
        ["vim"] = "",
        ["vimrc"] = "",
        ["vue"] = "󰡄",
        ["wav"] = "",
        ["webm"] = "",
        ["webmanifest"] = "",
        ["webp"] = "",
        ["wps"] = "",
        ["wpt"] = "",
        ["xbps"] = "",
        ["xcplayground"] = "",
        ["xhtml"] = "",
        ["xla"] = "󰈛",
        ["xlam"] = "󰈛",
        ["xls"] = "󰈛",
        ["xlsb"] = "󰈛",
        ["xlsm"] = "󰈛",
        ["xlsx"] = "󰈛",
        ["xlt"] = "󰈛",
        ["xltm"] = "󰈛",
        ["xltx"] = "󰈛",
        ["xml"] = "",
        ["xul"] = "",
        ["xz"] = "",
        ["yaml"] = "",
        ["yml"] = "",
        ["youtube"] = "",
        ["zip"] = "",
        ["zsh"] = "",
    };

    /// <summary>Glyphs by directory name.</summary>
    private static readonly Dictionary<string, string> Directories =
        new(StringComparer.Ordinal)
    {
        [".git"] = "",
        ["Desktop"] = "",
        ["Documents"] = "",
        ["Dotfiles"] = "",
        ["Downloads"] = "",
        ["Dropbox"] = "",
        ["Music"] = "",
        ["OneDrive"] = "",
        ["Pictures"] = "",
        ["Public"] = "",
        ["Templates"] = "",
        ["Videos"] = "",
        ["anaconda3"] = "",
        ["go"] = "",
        ["workspace"] = "",
    };
}
