#!/usr/bin/env python3
"""Generates Canger's special-key table from ranger's own keybinding_parser.

The table is transcribed mechanically rather than by hand so that Canger's key names, numeric
values and display strings match ranger exactly. Several entries are easy to get wrong by hand:
`c-_` is -1 because `ord('_') - 96` underflows, and the reverse mappings of 9 and 10 resolve to
`c-i` and `c-j` rather than `tab` and `return`, because the control-key entries are defined after
the base table and overwrite it.

Usage: tools/generate-special-keys.py ../ranger-master > src/Canger.Core/Input/SpecialKeys.g.cs
"""
import sys

sys.path.insert(0, sys.argv[1] if len(sys.argv) > 1 else "../ranger-master")
from ranger.ext.keybinding_parser import special_keys, reversed_special_keys  # noqa: E402


def esc(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


ints = [(k, v) for k, v in special_keys.items() if isinstance(v, int)]
tups = [(k, v) for k, v in special_keys.items() if isinstance(v, tuple)]

out = sys.stdout.write

out('''// SPDX-License-Identifier: GPL-3.0-or-later
// <auto-generated>
//   Generated from ranger's keybinding_parser.py by tools/generate-special-keys.py.
//   Do not edit by hand.
// </auto-generated>
using System.Collections.Frozen;

namespace Canger.Core.Input;

/// <summary>
/// The names accepted inside angle brackets in a key binding, and how key codes are rendered
/// back into those names.
/// </summary>
public static class SpecialKeys
{
''')

out("    /// <summary>Names that resolve to a single key code.</summary>\n")
out("    public static readonly FrozenDictionary<string, int> Single =\n")
out("        new Dictionary<string, int>(StringComparer.Ordinal)\n        {\n")
for k, v in ints:
    out(f'            ["{esc(k)}"] = {v},\n')
out("        }.ToFrozenDictionary(StringComparer.Ordinal);\n\n")

out('''    /// <summary>
    /// Names that resolve to a sequence of key codes. Every one of these is an Alt combination,
    /// which arrives as the Alt marker followed by the key it modifies.
    /// </summary>
''')
out("    public static readonly FrozenDictionary<string, int[]> Sequence =\n")
out("        new Dictionary<string, int[]>(StringComparer.Ordinal)\n        {\n")
for k, v in tups:
    out(f'            ["{esc(k)}"] = [{", ".join(str(x) for x in v)}],\n')
out("        }.ToFrozenDictionary(StringComparer.Ordinal);\n\n")

out('''    /// <summary>
    /// How each key code is rendered when a binding is shown back to the user, in the key buffer
    /// on the title bar and in the hint list.
    /// </summary>
    /// <remarks>
    /// Where several names share a code the last one defined wins, which is why 9 renders as
    /// <c>c-i</c> rather than <c>tab</c> and 10 as <c>c-j</c> rather than <c>return</c>.
    /// </remarks>
''')
out("    public static readonly FrozenDictionary<int, string> Names =\n")
out("        new Dictionary<int, string>\n        {\n")
for v, k in sorted((v, k) for v, k in reversed_special_keys.items() if isinstance(v, int)):
    out(f'            [{v}] = "{esc(k)}",\n')
out("        }.ToFrozenDictionary();\n}\n")
