#!/usr/bin/env python3
"""Generates the devicons linemode from ranger_devicons' own tables.

Reads the plugin's Python source and emits C#, so the ~400 glyph mappings are never transcribed
by hand. Run again to pick up a newer version of the plugin.

Usage: generate-devicons.py <path-to-devicons.py> <output.cs>
"""
import ast
import sys


def table(tree, name):
    """Reads a dict literal assigned to `name` at module level."""
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
                isinstance(t, ast.Name) and t.id == name for t in node.targets):
            if isinstance(node.value, ast.Dict):
                return {
                    ast.literal_eval(k): ast.literal_eval(v)
                    for k, v in zip(node.value.keys, node.value.values)
                    if isinstance(k, ast.Constant) and isinstance(v, ast.Constant)
                }
    return {}


def escape(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def emit(entries, indent="        "):
    return "\n".join(
        f'{indent}["{escape(k)}"] = "{escape(v)}",' for k, v in sorted(entries.items()))


source, output = sys.argv[1], sys.argv[2]
tree = ast.parse(open(source, encoding="utf-8").read())

extensions = table(tree, "file_node_extensions")
exact = table(tree, "file_node_exact_matches")
dirs = table(tree, "dir_node_exact_matches_base")

with open(output, "w", encoding="utf-8") as f:
    f.write(f"""// SPDX-License-Identifier: GPL-3.0-or-later
// <auto-generated>
//     Generated by tools/generate-devicons.py from ranger_devicons' devicons.py.
//     {len(exact)} exact names, {len(extensions)} extensions, {len(dirs)} directory names.
//     Do not edit by hand; regenerate instead.
// </auto-generated>
using System.Collections.Frozen;

namespace Canger.Core.Model;

/// <summary>
/// The glyph tables behind the <c>devicons</c> linemode.
/// </summary>
/// <remarks>
/// Copied from ranger_devicons, which took them from vim-devicons. Generated rather than typed:
/// there are several hundred, and a transcription error would show as one wrong icon that nobody
/// would ever track down.
/// </remarks>
internal static class DeviconTables
{{
    /// <summary>Glyphs for whole filenames, which win over the extension.</summary>
    internal static readonly FrozenDictionary<string, string> ExactNames =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {{
{emit(exact)}
        }}.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);

    /// <summary>Glyphs for filename extensions.</summary>
    internal static readonly FrozenDictionary<string, string> Extensions =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {{
{emit(extensions)}
        }}.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);

    /// <summary>Glyphs for well-known directory names.</summary>
    internal static readonly FrozenDictionary<string, string> Directories =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {{
{emit(dirs)}
        }}.ToFrozenDictionary(StringComparer.Ordinal);
}}
""")

print(f"{len(exact)} exact, {len(extensions)} extensions, {len(dirs)} directories")
