#!/usr/bin/env python3
"""Generates a self-contained Canger plugin from ranger_devicons' own tables.

The same source as generate-devicons.py, but emitting a plugin rather than a core file: one .cs
with its own tables and no dependency on Canger's internals, so it can be dropped into
~/.config/canger/plugins/ and edited freely.

Usage: generate-devicons-plugin.py <path-to-devicons.py> <output.cs>
"""
import ast
import sys


def table(tree, name):
    """Reads a dict literal assigned to `name` at module level."""
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
                isinstance(t, ast.Name) and t.id == name for t in node.targets):
            if isinstance(node.value, ast.Dict):
                return {
                    ast.literal_eval(k): ast.literal_eval(v)
                    for k, v in zip(node.value.keys, node.value.values)
                    if isinstance(k, ast.Constant) and isinstance(v, ast.Constant)
                }
    return {}


def escape(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def emit(entries, indent="        "):
    return "\n".join(
        f'{indent}["{escape(k)}"] = "{escape(v)}",' for k, v in sorted(entries.items()))


source, output = sys.argv[1], sys.argv[2]
tree = ast.parse(open(source, encoding="utf-8").read())

extensions = table(tree, "file_node_extensions")
exact = table(tree, "file_node_exact_matches")
dirs = table(tree, "dir_node_exact_matches_base")

with open(output, "w", encoding="utf-8") as f:
    f.write(f"""// SPDX-License-Identifier: GPL-3.0-or-later
//
// Devicons for Canger — a glyph before each name saying what kind of file it is.
//
// Generated by tools/generate-devicons-plugin.py from ranger_devicons' devicons.py:
// {len(exact)} exact names, {len(extensions)} extensions, {len(dirs)} directory names. The glyphs
// and the tables are ranger_devicons' work, GPL-3.0, and the glyphs themselves come from Nerd
// Fonts. Without a patched font they render as replacement boxes.
//
// Registered as "devicons", which is the name the built-in linemode uses, so this replaces it —
// `LinemodeRegistry.Register` overwrites a mode of the same name. Turn it on with
// `default_linemode devicons` in cc.conf, or `:linemode devicons` for one directory.
//
// Adding your own: put it in the right table below and restart. A whole filename beats an
// extension, which is how Makefile and .gitignore work. Regenerating from a newer
// ranger_devicons overwrites this file, so keep additions in a second plugin that falls back to
// this one if you expect to regenerate.
using Canger.Core.Model;
using Canger.Core.State;

/// <summary>A glyph before each name, from ranger_devicons' tables.</summary>
public sealed class DeviconsPlugin : ILinemode
{{
    /// <inheritdoc />
    public string Name => "devicons";

    /// <inheritdoc />
    public string Title(FsNode node, FileMetadata metadata, in LinemodeContext context)
    {{
        ArgumentNullException.ThrowIfNull(node);

        return Glyph(node) + " " + node.RelativePath;
    }}

    /// <inheritdoc />
    /// <remarks>
    /// Null rather than a value: the column falls back to the size, so this mode changes the name
    /// and leaves the right-hand side as an ordinary listing shows it.
    /// </remarks>
    public string? Detail(FsNode node, FileMetadata metadata, in LinemodeContext context) => null;

    /// <summary>The glyph for an entry.</summary>
    /// <param name="node">The entry.</param>
    /// <returns>A single glyph, or a generic one when nothing matches.</returns>
    public static string Glyph(FsNode node)
    {{
        ArgumentNullException.ThrowIfNull(node);

        string name = node.RelativePath;

        if (node.IsDirectory)
        {{
            return Directories.TryGetValue(name, out string? directory)
                ? directory
                : GenericDirectory;
        }}

        // A whole filename beats an extension: Makefile and .gitignore have no useful extension,
        // and Dockerfile would otherwise look like any other extensionless file.
        if (ExactNames.TryGetValue(name, out string? byName))
        {{
            return byName;
        }}

        string extension = System.IO.Path.GetExtension(name);

        return extension.Length > 1 && Extensions.TryGetValue(extension[1..], out string? byKind)
            ? byKind
            : GenericFile;
    }}

    /// <summary>Shown for a file nothing else matches.</summary>
    private const string GenericFile = "";

    /// <summary>Shown for a directory nothing else matches.</summary>
    private const string GenericDirectory = "";

    /// <summary>Glyphs by whole filename.</summary>
    private static readonly Dictionary<string, string> ExactNames =
        new(StringComparer.OrdinalIgnoreCase)
    {{
{emit(exact)}
    }};

    /// <summary>Glyphs by extension, without the dot.</summary>
    private static readonly Dictionary<string, string> Extensions =
        new(StringComparer.OrdinalIgnoreCase)
    {{
{emit(extensions)}
    }};

    /// <summary>Glyphs by directory name.</summary>
    private static readonly Dictionary<string, string> Directories =
        new(StringComparer.Ordinal)
    {{
{emit(dirs)}
    }};
}}
""")

print(f"{output}: {len(exact)} exact names, {len(extensions)} extensions, {len(dirs)} directories")
