#!/usr/bin/env python3
"""Generates the East Asian Width table Canger uses to measure text in terminal cells.

.NET has no equivalent of Python's unicodedata.east_asian_width, so the ranges are emitted as a
sorted table and looked up by binary search at run time.

Ranger treats categories W (Wide) and F (Fullwidth) as two cells and everything else as one
(ext/widestring.py:13-29). Canger matches that exactly, because the value decides column
alignment and any difference would make listings line up differently from ranger.

Usage: tools/generate-east-asian-width.py > src/Canger.Tui/Text/EastAsianWidth.g.cs
"""
import sys
import unicodedata

WIDE = {"W", "F"}

ranges = []
start = None
for code in range(0x110000):
    wide = unicodedata.east_asian_width(chr(code)) in WIDE
    if wide and start is None:
        start = code
    elif not wide and start is not None:
        ranges.append((start, code - 1))
        start = None
if start is not None:
    ranges.append((start, 0x10FFFF))

out = sys.stdout.write
out(f'''// SPDX-License-Identifier: GPL-3.0-or-later
// <auto-generated>
//   Generated by tools/generate-east-asian-width.py from Unicode {unicodedata.unidata_version}.
//   Do not edit by hand.
// </auto-generated>
namespace Canger.Tui.Text;

/// <summary>
/// The code point ranges that occupy two terminal cells rather than one.
/// </summary>
/// <remarks>
/// These are the Unicode East Asian Width categories W (Wide) and F (Fullwidth), the same two
/// ranger treats as double width (<c>ext/widestring.py:13-29</c>). Matching that choice matters:
/// the value decides how wide a filename is considered to be, so a different rule would make
/// columns line up differently from ranger.
/// </remarks>
internal static class EastAsianWidth
{{
    /// <summary>The Unicode version this table was generated from.</summary>
    internal const string UnicodeVersion = "{unicodedata.unidata_version}";

    /// <summary>
    /// Inclusive start and end of each double-width range, sorted, for binary search.
    /// </summary>
    internal static ReadOnlySpan<int> Ranges =>
    [
''')
for lo, hi in ranges:
    out(f"        0x{lo:04X}, 0x{hi:04X},\n")
out("    ];\n}\n")
