#!/usr/bin/env python3
"""Generates Canger's colour context keys from ranger's gui/context.py.

A colourscheme decides a cell's colours from the set of context keys that apply to it — whether
it is a directory, whether it is selected, which widget it is in, and so on. Generating the list
keeps Canger's keys identical to ranger's, so a colourscheme ported from ranger means the same
thing here.

Usage: tools/generate-context-keys.py ../ranger-master > src/Canger.Ui/Styling/ContextKey.g.cs
"""
import re
import sys
import pathlib

root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "../ranger-master")
src = (root / "ranger/gui/context.py").read_text()
start = src.index("CONTEXT_KEYS = [")
keys = re.findall(r"'([a-z_0-9]+)'", src[start:src.index("]", start)])

seen, ordered = set(), []
for key in keys:
    if key not in seen:
        seen.add(key)
        ordered.append(key)

assert len(ordered) <= 128, "StyleContext stores keys in two 64-bit words"


def pascal(name):
    return "".join(part.capitalize() for part in name.split("_"))


# Names that read poorly under blind capitalisation, or that ranger itself misspells.
overrides = {
    "seperator": "Separator",       # ranger's spelling; corrected here, value unchanged
    "vcsfile": "VcsFile",
    "vcsremote": "VcsRemote",
    "vcsinfo": "VcsInfo",
    "vcscommit": "VcsCommit",
    "vcsdate": "VcsDate",
    "vcsconflict": "VcsConflict",
    "vcschanged": "VcsChanged",
    "vcsunknown": "VcsUnknown",
    "vcsignored": "VcsIgnored",
    "vcsuntracked": "VcsUntracked",
    "vcsstaged": "VcsStaged",
    "vcssync": "VcsSync",
    "vcsnone": "VcsNone",
    "vcsbehind": "VcsBehind",
    "vcsahead": "VcsAhead",
    "vcsdiverged": "VcsDiverged",
    "badinfo": "BadInfo",
    "infostring": "InfoString",
    "keybuffer": "KeyBuffer",
    "nlink": "LinkCount",
}

out = sys.stdout.write
out(f'''// SPDX-License-Identifier: GPL-3.0-or-later
// <auto-generated>
//   Generated from ranger's gui/context.py by tools/generate-context-keys.py.
//   Do not edit by hand.
// </auto-generated>
namespace Canger.Ui.Styling;

/// <summary>
/// The properties a colourscheme can colour by.
/// </summary>
/// <remarks>
/// Several of these apply to a cell at once — a row might be in the browser, in the main column,
/// a directory, and selected — and the colourscheme decides the result from the whole set rather
/// than from any one key. The names and the set match ranger's exactly, so a colourscheme ported
/// from there means the same thing here.
/// </remarks>
public enum ContextKey
{{
''')

for index, key in enumerate(ordered):
    name = overrides.get(key, pascal(key))
    out(f'    /// <summary>The <c>{key}</c> context.</summary>\n')
    out(f'    {name} = {index},\n\n')

out("}\n\n")

out('''/// <summary>Maps context keys to and from the names used in configuration.</summary>
public static class ContextKeys
{
    /// <summary>How many keys there are.</summary>
''')
out(f"    public const int Count = {len(ordered)};\n\n")
out("    private static readonly string[] NamesByKey =\n    [\n")
for key in ordered:
    out(f'        "{key}",\n')
out("    ];\n\n")
out('''    /// <summary>The configuration name of a key.</summary>
    /// <param name="key">The key.</param>
    /// <returns>Its name, as ranger spells it.</returns>
    public static string NameOf(ContextKey key) => NamesByKey[(int)key];

    /// <summary>Every key, in declaration order.</summary>
    public static IReadOnlyList<ContextKey> All { get; } =
        [.. Enumerable.Range(0, Count).Select(i => (ContextKey)i)];
}
''')
